try{
    anotherFunction()
} catch (e) {
    console.log("Error");
}   

try {
    console.log('lagarto');
} catch(e) {
    console.log('F por el hello()!')
    console.log(e);
}